---
knit: pagedown::chrome_print
main_topsize: 0.09 #percent coverage of the poster
main_bottomsize: 0.03

# ESSENTIALS
title: ''
# author:
#   - name: '**Shi Hui Tan**'
main_findings: "**Vizing your Data!**"
bottom_findings: 'viz-1'
main_fontfamily: 'Satisfy'
poster_height: '11.69in'
poster_width: '8.27in'
column_numbers: 1

# COLOUR SCHEME
#2DF7A1
primary_colour: '#E7699E30'
secondary_colour: '#DDE76930' #'#DDCED4'
accent_colour: '#69E7B2'
main_textcol: '000000' #'#5F5459'
# #5F545930

# MAIN SECTION
main_textsize: '55px'

# BODY SECTION
title_textsize: '19px'
author_textsize: '1em'
body_textsize: '16px'
body_width: 1
font_family: 'Lato'

output: 
  posterdown::posterdown_betterport:
    self_contained: false
    pandoc_args: --mathjax
    number_sections: false
    export_pdf: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      tidy = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      out.width = "100%")
options(knitr.table.format = "html") 
```

# DENSITY

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(MASS)
library(ggplot2)
library(dplyr)
data(survey)
sampleData <- survey %>% filter(!is.na(Sex))
```

```{r plotting, message = FALSE, echo = FALSE, warning=FALSE, fig.height = 3.5}
ggplot(sampleData) +
  geom_density(aes(Height, fill=Sex), alpha=0.4) + 
  xlab('Height (cm)') + ylab('Density') + 
  theme_minimal() + 
  scale_fill_manual(values = c('Female'='firebrick2', 'Male' = 'dodgerblue2')) +
  theme(axis.text=element_text(size=12), axis.title = element_text(size=12), 
        legend.text = element_text(size=12), legend.title = element_text(size=12))
```
```{r plotting code, echo = TRUE, warning=FALSE, message=FALSE, eval=FALSE}
ggplot(sampleData) +
  geom_density(aes(Height, color=Sex, fill=Sex), alpha=0.4) + 
  xlab('Height (cm)') + ylab('Density') + 
  theme_minimal() + 
  scale_fill_manual(values = c('Female'='firebrick2', 
                               'Male' = 'dodgerblue2')) +
  theme(axis.text=element_text(size=12), 
        axis.title = element_text(size=12), 
        legend.text = element_text(size=12), 
        legend.title = element_text(size=12))
```


# plot information
```{r info table, results='asis', include=TRUE}
library(kableExtra)
library(dplyr)
infoCard <- data.frame(title = c('About \r\n\r\n', 
                     'Common usage \r\n\r\n', 
                     'Number of / \r\nType of Variables \r\n\r\n', 
                     'R Package \r\n\r\n', 
                     'R Function'),
           info = c('A density plot visualizes the distribution of a numeric variable over a continuous interval. A variation of histogram, density plot serves better in determining the distribution shape of data. <br<br><br>', 
                    'Comparing distributions of a variable between groups <br<br>',
                    '<ul><li> 1 numeric <br><li> 1 per numeric and categorical <br<br>', 
                    'ggplot2<br<br><br>',
                    'geom_density'))
infoCard %>% mutate(title = cell_spec(title, color = "#E7699E", bold = T)) %>% kable(col.names = c('',''), align = 'l', escape=FALSE, booktabs=TRUE, format='html') %>% column_spec(column=1, width = '4.5cm') %>% 
  column_spec(column=2, width = '13cm')
```
